### ISSUE TITLE
optfile example missing

### ISSUE THREAD

**Issue by jachym** [maptiler/manual#4]
I did not find any example of the optfile metioned in the documentation http://maptiler.readthedocs.io/en/stable/usage.html?highlight=optfile#options-in-the-optfile

I've tried

```
file1.tiff -b 1 -b 2 -b 3 -b 5 
file2.tiff -b 1 -b 2 -b 3 -b 5 
file3.tiff -b 1 -b 2 -b 3 -b 5
...
```

but it did not seem to be working

**Comment by MartinMikita** [comment]
This optfile looks good. The problem could be with running in docker and using relative paths outside of mounted paths.
